Repository Helixis/CEV-Eris, pull requests merged in 2020-09, with the labels that each got.

#23 Bebida Agridulce
  cev_eris.dme
  code/hispania/modules/reagents/reagent_containers/food/cans.dm
  icons/hispania/obj/drinks.dmi
Labels: Feature, Sprites

#24 el mimo ahora es elegible como narrador
  code/game/gamemodes/storytellers/mime.dm
Labels: Tweak

#25 Update card.dmi
  code/game/objects/items/weapons/cards_ids.dm
  icons/hispania/obj/card.dmi
Labels: Sprites

#26 FINALMENTE, MILANESAS V2
  cev_eris.dme
  code/game/machinery/vending.dm
  code/hispania/game/objects/items/weapons/kitchen.dm
  code/hispania/modules/food/food.dm
  code/hispania/modules/food/recipes_microwave.dm
  icons/hispania/obj/food/food.dmi
  icons/hispania/obj/kitchen.dmi
Labels: Feature, Sprites

#28 Los especimenes más grandes de cucarachas ahora son densos
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
Labels: Balance

#27 baja los rates de las cucarachas y arañas
  code/game/objects/random/mob/roach.dm
  code/game/objects/random/mob/spider.dm
Labels: Balance

#29 Acceso a maint para todo med y ciencias
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
Labels: Balance

#31 Droids skins
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/hispania/mob/robots.dmi
Labels: Sprites

#32 WIP Borg Weapons
  cev_eris.dme
  code/hispania/game/objects/items/weapons/guns/energy/egun.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
Labels: Feature, Revert, WIP

#33 Cucarachas Generacionales
  code/game/objects/effects/roaches.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
Labels: Feature
