Repository Helixis/CEV-Eris, pull requests merged in 2020-10, with the labels that each got.

#36 Ajuste de Consumo
  code/hispania/game/objects/items/weapons/guns/energy/egun.dm
Labels: ???, Tweak

#39 Balanceo del arma de los borg.
  code/hispania/game/objects/items/weapons/guns/energy/egun.dm
Labels: Balance

#37 Evan infiernito presenta: Skrells
  cev_eris.dme
  code/__DEFINES/chemistry.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mob_species_forms.dm
  code/__DEFINES/species_languages.dm
  code/controllers/subsystems/jobs.dm
  code/datums/datacore.dm
  code/game/dna/dna2.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/hispania/modules/mob/language/station.dm
  code/hispania/modules/mob/living/carbon/human/species/station/station.dm
  code/hispania/modules/organs/internal/kidan.dm
  code/hispania/modules/organs/internal/skrell.dm
  code/hispania/modules/sprite_accessories/kidan/kidan_facial.dm
  code/hispania/modules/sprite_accessories/kidan/kidan_hair.dm
  code/hispania/modules/sprite_accessories/skrell/skrell_face.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/sprite_accessories/_accessory.dm
  icons/hispania/mob/human_face.dmi
  icons/hispania/mob/human_races/r_def_skrell.dmi
  icons/hispania/mob/human_races/r_skrell.dmi
  icons/hispania/mob/human_races/species/skrell/skrell_hair.dmi
  icons/hispania/mob/kidan_face.dmi
  icons/hispania/obj/species/organs/kidan.dmi
  icons/hispania/obj/species/organs/skrell.dmi
Labels: Feature, Fix

#41 edad ideal de los heads por raza
  cev_eris.dme
  code/controllers/subsystems/jobs.dm
  code/hispania/controllers/subsystems/jobs.dm
Labels: Tweak
